# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 21:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateField(verbose_name=['%d-%m-%Y', '%d.%m.%Y', '%d/%m/%Y']),
        ),
    ]
