# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 21:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost', '0002_auto_20161026_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.DateField(blank=True, verbose_name=['%d-%m-%Y', '%d.%m.%Y', '%d/%m/%Y']),
        ),
        migrations.AlterField(
            model_name='data',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='descriptor_image',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='data',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='data',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='data',
            name='rollno',
            field=models.IntegerField(blank=True),
        ),
    ]
